misc: rename library to solar_client
Solar-network/python-client pull request #7
Opened 2022-06-12 08:23 UTC by c0nsol3

2022-06-13 16:01 UTC, sleepdefic1t commented
@c0nsol3 
Can you revert the formatting changes in `solar_client/api/delegates.py`, please and thank you 🙏 

It's only one file but the application of formatting should be a separate thing.

2022-06-13 16:05 UTC, c0nsol3 commented
@sleepdefic1t done

2022-06-15 07:09 UTC, sleepdefic1t requested changes

2022-06-15 07:09 UTC, sleepdefic1t commented on README.md
> +from client.client import SolarClient
Should this be `solar_client`?
```diff
- from client.client import SolarClient
+ from solar_client.client import SolarClient
```

2022-06-15 08:20 UTC, c0nsol3 commented
@sleepdefic1t done

2022-06-15 16:39 UTC, sleepdefic1t approved these changes

2022-06-15 21:58 UTC, Cactus-15-49 approved these changes

2022-06-15 22:37 UTC, merged